sudo: false

language: generic

matrix:
  include:
    - env: EMACS=emacs24
      addons:
        apt:
          sources: [ { sourceline: 'ppa:cassou/emacs' } ]
          packages: [ emacs24, emacs24-el ]
    - env: EMACS=emacs25
      addons:
        apt:
          sources: [ { sourceline: 'ppa:kelleyk/emacs' } ]
          packages: [ emacs25 ]
    - env: EMACS=emacs-snapshot
      addons:
        apt:
          sources: [ { sourceline: 'ppa:ubuntu-elisp/ppa' } ]
          packages: [ emacs-snapshot ]

install: true

script:
  make test-batch EMACS=${EMACS}
